import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, randomBytes } from 'node:crypto';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import mysql from 'mysql2/promise';
import bcrypt from 'bcryptjs';
import ExcelJS from 'exceljs';

test('Luồng chức năng đầy đủ trên MySQL cô lập qua HTTP', { skip: process.env.MYSQL_INTEGRATION_TEST !== 'true', timeout: 120000 }, async t => {
  const port = Number(process.env.INTEGRATION_MYSQL_PORT), expected = process.env.INTEGRATION_MYSQL_DATADIR;
  assert.ok(port > 1024 && port !== 3306 && expected?.includes('tinhdoan-mysql-integration-'), 'Chỉ chạy trên MySQL kiểm thử được chỉ định rõ.');
  const connection = await mysql.createConnection({ host: '127.0.0.1', port, user: 'root', password: '' });
  const [[location]] = await connection.query('SELECT @@datadir AS datadir');
  const normalized = value => path.resolve(value).replace(/[\\/]+$/, '').toLowerCase();
  assert.equal(normalized(location.datadir), normalized(expected));
  await connection.end();
  Object.assign(process.env, { DB_HOST: '127.0.0.1', DB_PORT: String(port), DB_USER: 'root', DB_PASSWORD: '', DB_NAME: `features_integration_${randomUUID().replaceAll('-', '')}`, NODE_ENV: 'test', JWT_SECRET: randomBytes(48).toString('hex'), OTP_ENABLED: 'false', OTP_DEV_MODE: 'false', UPLOAD_DIR: await mkdtemp(path.join(tmpdir(), 'tinhdoan-feature-assets-')) });
  const { initializeDatabase, closeDatabase, pool } = await import('../src/db.js');
  const { createApp } = await import('../src/app.js');
  const { finalizeExpiredSessions } = await import('../src/exam/exam-service.js');
  const { finalizeEndedRounds } = await import('../src/exam/rounds.js');
  await initializeDatabase();
  t.after(closeDatabase);
  const server = createApp({ pool, sendOtpEmail: async () => { throw new Error('Không được gửi OTP khi đã tắt.'); } }).listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}/api`;
  const call = async (url, { token, body, method = body === undefined ? 'GET' : 'POST', status = 200, form } = {}) => {
    const response = await fetch(`${base}${url}`, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body !== undefined && !form ? { 'Content-Type': 'application/json' } : {}) }, ...(form ? { body: form } : body !== undefined ? { body: JSON.stringify(body) } : {}) });
    const payload = await response.json();
    assert.equal(response.status, status, `${method} ${url}: ${JSON.stringify(payload)}`);
    return payload;
  };
  const password = 'KiemThu-Password-2026';
  const [createdAdmin] = await pool.query("INSERT INTO users (hoten,dienthoai,email,password,is_active,role) VALUES ('Quản trị kiểm thử','0900000100','admin@test.example',?,1,'admin')", [await bcrypt.hash(password, 12)]);
  const admin = (await call('/auth/login', { body: { identifier: '0900000100', password } })).token;
  const unit = (await call('/manage/units', { token: admin, body: { ten: 'Đơn vị kiểm thử', organizationName: 'Đoàn kiểm thử' }, status: 201 })).item;
  let candidate, candidateId, competition, questions, session, teacher, teacherId;

  await t.test('Đăng ký không OTP; vai trò không được lấy từ trình duyệt; logout chỉ một phiên', async () => {
    const registration = await call('/auth/register', { body: { hoten: 'Thí sinh kiểm thử', dienthoai: '0900000101', email: 'candidate@test.example', password, donviID: unit.id, role: 'admin' }, status: 201 });
    assert.notEqual(registration.registrationPending, true);
    const login = await call('/auth/login', { body: { identifier: '0900000101', password } });
    candidate = login.token; candidateId = login.user.id;
    assert.equal(login.user.role, 'candidate');
    const other = (await call('/auth/login', { body: { identifier: 'candidate@test.example', password } })).token;
    await call('/auth/logout', { token: other, body: {} });
    await call('/auth/me', { token: other, status: 401 });
    await call('/auth/me', { token: candidate });
    const [[{ count }]] = await pool.query('SELECT COUNT(*) AS count FROM otp_verifications');
    assert.equal(Number(count), 0);
    await call('/manage/users', { token: candidate, status: 403 });
  });
  await t.test('Tạo kỳ thi, câu hỏi và import Excel toàn bộ hoặc không lưu', async () => {
    competition = (await call('/manage/competitions', { token: admin, status: 201, body: { name: 'Kỳ thi tích hợp', description: 'Kiểm thử chức năng', startAt: new Date(Date.now() - 60000).toISOString(), endAt: new Date(Date.now() + 3600000).toISOString(), durationMinutes: 30, maxAttempts: 2, status: 'published' } })).item;
    const invalid = { competitionId: competition.id, content: 'Câu kiểm thử', optionA: 'A', optionB: 'B', optionC: 'C', optionD: 'D', correctAnswer: 'E', difficulty: 'easy' };
    await call('/manage/questions', { token: admin, body: invalid, status: 400 });
    await call('/manage/questions', { token: admin, body: { ...invalid, correctAnswer: 'A' }, status: 201 });
    const response = await fetch(`${base}/manage/questions/template`, { headers: { Authorization: `Bearer ${admin}` } });
    assert.equal(response.status, 200);
    const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(Buffer.from(await response.arrayBuffer()));
    workbook.worksheets[0].getRow(2).getCell(6).value = 'Z';
    const makeForm = async () => { const form = new FormData(); form.append('file', new Blob([await workbook.xlsx.writeBuffer()]), 'cau-hoi.xlsx'); return form; };
    await call(`/manage/questions/import?competitionId=${competition.id}`, { token: admin, method: 'POST', form: await makeForm(), status: 400 });
    assert.equal((await call(`/manage/questions?competitionId=${competition.id}`, { token: admin })).total, 1);
    workbook.worksheets[0].getRow(2).getCell(6).value = 'C';
    await call(`/manage/questions/import?competitionId=${competition.id}`, { token: admin, method: 'POST', form: await makeForm(), status: 201 });
    questions = (await call(`/manage/questions?competitionId=${competition.id}`, { token: admin })).items;
    assert.equal(questions.length, 2);
    await call('/manage/exams/preview', { token: admin, body: { competitionId: competition.id, count: 3 }, status: 409 });
    const preview = await call('/manage/exams/preview', { token: admin, body: { competitionId: competition.id, count: 2, quantity: 2 } });
    assert.equal(preview.items.length, 2);
    const published = await call('/manage/exams', { token: admin, body: { competitionId: competition.id, items: preview.items.map(item => ({ name: item.name, questionIds: item.questions.map(q => q.id) })) }, status: 201 });
    assert.equal(published.items.length, 2);
  });
  await t.test('Cấp giảng viên, bắt đổi mật khẩu và giới hạn phạm vi', async () => {
    const account = await call('/manage/users', { token: admin, body: { hoten: 'Giảng viên kiểm thử', dienthoai: '0900000102', email: 'teacher@test.example', role: 'teacher', permissions: ['questions', 'exams', 'candidates', 'reports'], competitionIds: [competition.id] }, status: 201 });
    teacherId = account.item.id;
    const temp = (await call('/auth/login', { body: { identifier: '0900000102', password: account.temporaryPassword } })).token;
    await call('/manage/questions', { token: temp, status: 403 });
    await call('/auth/change-password', { token: temp, body: { currentPassword: account.temporaryPassword, newPassword: password } });
    await call('/auth/me', { token: temp, status: 401 });
    teacher = (await call('/auth/login', { body: { identifier: '0900000102', password } })).token;
    assert.equal((await call('/manage/competitions', { token: teacher })).items.length, 1);
    await call('/manage/competitions', { token: teacher, body: {}, status: 403 });
    await call('/manage/questions', { token: teacher, body: { ...questions[0], competitionId: 999999 }, status: 403 });
    await call('/manage/users', { token: teacher, status: 403 });
  });
  await t.test('Đăng ký kỳ thi một lần, start đồng thời một phiên, chống ghi đè và lộ đáp án', async () => {
    const blocked = await call(`/candidate/competitions/${competition.id}/start`, { token: candidate, body: {}, status: 403 });
    assert.equal(blocked.code, 'REGISTRATION_REQUIRED');
    await call(`/candidate/competitions/${competition.id}/register`, { token: candidate, body: {} });
    await call(`/candidate/competitions/${competition.id}/register`, { token: candidate, body: {} });
    const [first, second] = await Promise.all([call(`/candidate/competitions/${competition.id}/start`, { token: candidate, body: {} }), call(`/candidate/competitions/${competition.id}/start`, { token: candidate, body: {} })]);
    session = first.item;
    assert.equal(String(first.item.id), String(second.item.id));
    assert.ok(session.questions.every(q => !('correctAnswer' in q)));
    const answers = Object.fromEntries(questions.map(q => [q.id, q.correctAnswer]));
    session = (await call(`/candidate/sessions/${session.id}/answers`, { token: candidate, method: 'PUT', body: { revision: session.revision, answers } })).item;
    const conflict = await call(`/candidate/sessions/${session.id}/answers`, { token: candidate, method: 'PUT', body: { revision: session.revision - 1, answers: {} }, status: 409 });
    assert.deepEqual(conflict.item.answers, answers);
    assert.deepEqual((await call(`/candidate/sessions/${session.id}`, { token: candidate })).item.answers, answers);
    await call(`/manage/questions/${questions[0].id}`, { token: admin, method: 'PUT', body: { ...questions[0], correctAnswer: questions[0].correctAnswer === 'A' ? 'B' : 'A' } });
    await call(`/manage/questions/${questions[1].id}`, { token: admin, method: 'DELETE' });
    const submitted = await Promise.all([1, 2].map(() => call(`/candidate/sessions/${session.id}/submit`, { token: candidate, body: { answers, revision: session.revision } })));
    assert.ok(submitted.every(result => result.item.score === 100));
    const [[{ count }]] = await pool.query('SELECT COUNT(*) AS count FROM results WHERE session_id=?', [session.id]);
    assert.equal(Number(count), 1);
    await call(`/manage/competitions/${competition.id}`, { token: admin, method: 'PUT', body: { ...competition, durationMinutes: 31 }, status: 409 });
  });
  await t.test('Worker nộp hết giờ; không nhận đáp án muộn; đủ lượt thì từ chối', async () => {
    const second = (await call(`/candidate/competitions/${competition.id}/start`, { token: candidate, body: {} })).item;
    await pool.query('UPDATE user_exam_sessions SET expires_at=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE id=?', [second.id]);
    await finalizeExpiredSessions(pool);
    const late = (await call(`/candidate/sessions/${second.id}/submit`, { token: candidate, body: { revision: 0, answers: Object.fromEntries(questions.map(q => [q.id, q.correctAnswer])) } })).item;
    assert.equal(late.status, 'expired'); assert.equal(late.score, 0);
    await call(`/candidate/competitions/${competition.id}/start`, { token: candidate, body: {}, status: 409 });
    const results = (await call(`/candidate/results?competitionId=${competition.id}`, { token: candidate })).items;
    assert.equal(results.length, 2);
    assert.deepEqual(results.map(item => item.score).sort((a,b)=>a-b), [0, 100]);
  });
  await t.test('Thống kê đúng, export XLSX và giảng viên chỉ thấy phạm vi phân công', async () => {
    const report = await call(`/reports?competitionId=${competition.id}`, { token: candidate });
    assert.deepEqual(report.summary, { registrations: 1, attempts: 2, completed: 2, averageScore: 50 });
    assert.equal(report.units[0].name, unit.ten);
    const scoped = await call('/manage/candidates', { token: teacher });
    assert.equal(scoped.total, 1); assert.equal(Number(scoped.items[0].id), Number(candidateId));
    await call('/reports/export', { token: candidate, status: 403 });
    const response = await fetch(`${base}/reports/export?competitionId=${competition.id}`, { headers: { Authorization: `Bearer ${teacher}` } });
    assert.equal(response.status, 200);
    const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(Buffer.from(await response.arrayBuffer()));
    assert.equal(workbook.worksheets[0].getRow(2).getCell(3).value, 2);
    await call('/reports?from=2026-02-30', { token: admin, status: 400 });
    await call(`/manage/users/${teacherId}/access`, { token: admin, method: 'PUT', body: { role: 'teacher', is_active: true, permissions: ['reports'], competitionIds: [] } });
    await call('/reports', { token: teacher, status: 401 });
    teacher = (await call('/auth/login', { body: { identifier: '0900000102', password } })).token;
    assert.equal((await call('/reports', { token: teacher })).summary.attempts, 0);
    await call(`/manage/users/${createdAdmin.insertId}/access`, { token: admin, method: 'PUT', body: { role: 'candidate', is_active: true, permissions: [], competitionIds: [] }, status: 409 });
  });
  await t.test('Banner, tin tức chỉ áp dụng sau xác nhận; từ chối tệp thực thi', async () => {
    const old = (await call('/site')).item;
    const form = new FormData(); form.append('kind', 'banner'); form.append('file', new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64')], { type: 'image/png' }), 'banner.png');
    const asset = (await call('/manage/assets', { token: admin, method: 'POST', form, status: 201 })).item;
    assert.equal((await call('/site')).item.bannerUrl, old.bannerUrl);
    await call('/manage/site', { token: admin, method: 'PUT', body: { title: 'Cổng thi mới', description: 'Đã áp dụng', bannerUrl: asset.url, newsUrl: '', newsTitle: '' } });
    assert.equal((await call('/site')).item.bannerUrl, asset.url);
    const response = await fetch(`${base}${asset.url.replace('/api', '')}`); assert.equal(response.status, 200); assert.match(response.headers.get('content-type'), /image\/png/);
    const bad = new FormData(); bad.append('kind', 'banner'); bad.append('file', new Blob(['<svg onload="alert(1)"></svg>']), 'banner.png');
    await call('/manage/assets', { token: admin, method: 'POST', form: bad, status: 400 });
    await call('/manage/site', { token: admin, method: 'PUT', body: { title: 'Tiêu đề', bannerUrl: 'https://example.com/tracker.png' }, status: 400 });
  });
  await t.test('Nhiều vòng: đúng ngân hàng, thời gian server, Top N và chống vượt vòng', async () => {
    const contest = (await call('/manage/competitions', { token: admin, status: 201, body: { name: 'Cuộc thi nhiều vòng', startAt: new Date(Date.now()-3600000).toISOString(), endAt: new Date(Date.now()+10800000).toISOString(), durationMinutes: 30, maxAttempts: 2, status: 'published' } })).item;
    const makeRound = (name,roundNumber,start,end,advanceCount) => call(`/manage/competitions/${contest.id}/rounds`,{token:admin,status:201,body:{name,roundNumber,startAt:new Date(Date.now()+start).toISOString(),endAt:new Date(Date.now()+end).toISOString(),durationMinutes:5,advanceCount}});
    const one=(await makeRound('Sơ loại',1,-1800000,1800000,1)).item;
    const two=(await makeRound('Chung kết',2,1801000,7200000,0)).item;
    const baseQuestion={competitionId:contest.id,content:'Câu hỏi riêng của vòng',optionA:'A',optionB:'B',optionC:'C',optionD:'D',correctAnswer:'A',difficulty:'easy'};
    await call('/manage/questions',{token:admin,status:400,body:baseQuestion});
    const q1=(await call('/manage/questions',{token:admin,status:201,body:{...baseQuestion,roundId:one.id}})).item;
    const q2=(await call('/manage/questions',{token:admin,status:201,body:{...baseQuestion,roundId:two.id,correctAnswer:'D'}})).item;
    const preview=(await call('/manage/exams/preview',{token:admin,body:{competitionId:contest.id,roundId:one.id,count:1,quantity:1}})).items;
    assert.equal(Number(preview[0].questions[0].id),Number(q1.id));
    await call('/manage/exams',{token:admin,status:409,body:{competitionId:contest.id,roundId:one.id,items:[{name:'Sai vòng',questionIds:[q2.id]}]}});
    for(const [round,q] of [[one,q1],[two,q2]]) await call('/manage/exams',{token:admin,status:201,body:{competitionId:contest.id,roundId:round.id,items:[{name:round.name,questionIds:[q.id]}]}});
    await call('/auth/register',{status:201,body:{hoten:'Thí sinh nhanh hơn',dienthoai:'0900000111',email:'fast@test.example',password,donviID:unit.id}});
    const faster=(await call('/auth/login',{body:{identifier:'0900000111',password}})).token;
    const roundStates = async token => (await call('/candidate/competitions',{token})).items.find(item=>Number(item.id)===Number(contest.id)).rounds;
    assert.equal((await roundStates(faster))[0].status,'LOCKED');
    for(const token of [candidate,faster]) await call(`/candidate/competitions/${contest.id}/register`,{token,body:{}});
    assert.deepEqual((await roundStates(faster)).map(round=>round.status),['AVAILABLE','LOCKED']);
    const first=(await call(`/candidate/competitions/${contest.id}/start`,{token:candidate,body:{roundId:one.id}})).item;
    assert.equal(Number(first.questions[0].id),Number(q1.id));
    await call(`/candidate/sessions/${first.id}/submit`,{token:candidate,body:{answers:{},revision:0}});
    const best=(await call(`/candidate/competitions/${contest.id}/start`,{token:candidate,body:{roundId:one.id}})).item;
    await pool.query('UPDATE user_exam_sessions SET started_at=DATE_SUB(NOW(),INTERVAL 30 SECOND) WHERE id=?',[best.id]);
    await call(`/candidate/sessions/${best.id}/submit`,{token:candidate,body:{answers:{[q1.id]:'A'},revision:0,score:999,durationSeconds:0}});
    assert.equal((await roundStates(candidate))[0].status,'COMPLETED');
    const fastSession=(await call(`/candidate/competitions/${contest.id}/start`,{token:faster,body:{roundId:one.id}})).item;
    await pool.query('UPDATE user_exam_sessions SET started_at=DATE_SUB(NOW(),INTERVAL 10 SECOND) WHERE id=?',[fastSession.id]);
    const fastResult=(await call(`/candidate/sessions/${fastSession.id}/submit`,{token:faster,body:{answers:{[q1.id]:'A'},revision:0}})).item;
    assert.equal(fastResult.score,100); assert.ok(fastResult.durationSeconds>=10&&fastResult.durationSeconds<15);
    await call(`/candidate/competitions/${contest.id}/start`,{token:faster,body:{roundId:two.id},status:403});
    await call(`/manage/competitions/${contest.id}/rounds/${one.id}/finalize`,{token:admin,body:{},status:409});
    // Đổi lịch trong database kiểm thử để không chờ hết thời lượng thực.
    await pool.query('UPDATE rounds SET end_datetime=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE id=?',[one.id]);
    await pool.query('UPDATE rounds SET start_datetime=NOW() WHERE id=?',[two.id]);
    const automaticFinalization = await finalizeEndedRounds(pool);
    assert.equal(automaticFinalization.finalized,1);
    assert.equal(automaticFinalization.waiting,0);
    const rankings=(await call(`/manage/competitions/${contest.id}/rounds/${one.id}/rankings`,{token:admin})).items;
    assert.equal(rankings.length,2); assert.equal(rankings[0].hoten,'Thí sinh nhanh hơn');
    assert.equal(Number(rankings[0].advanced),1); assert.equal(Number(rankings[1].advanced),0);
    assert.deepEqual((await roundStates(faster)).map(round=>round.status),['COMPLETED','AVAILABLE']);
    assert.deepEqual((await roundStates(candidate)).map(round=>round.status),['COMPLETED','LOCKED']);
    const rejected=await call(`/candidate/competitions/${contest.id}/start`,{token:candidate,body:{roundId:two.id,advanced:true,roundRank:1},status:403});
    assert.equal(rejected.code,'ROUND_NOT_QUALIFIED');
    const next=(await call(`/candidate/competitions/${contest.id}/start`,{token:faster,body:{roundId:two.id}})).item;
    assert.equal(Number(next.questions[0].id),Number(q2.id)); assert.equal(next.attemptNumber,1);
    const personal=(await call(`/candidate/results?competitionId=${contest.id}`,{token:faster})).items;
    assert.equal(personal[0].roundRank,1); assert.equal(personal[0].advanced,true); assert.ok(personal[0].startedAt); assert.ok(personal[0].durationSeconds>=10);
    const listing=(await call('/candidate/competitions',{token:faster})).items.find(c=>Number(c.id)===Number(contest.id));
    assert.equal(listing.rounds.length,2); assert.equal(Number(listing.currentRoundId),Number(two.id));
  });
  await t.test('Quên mật khẩu tạo yêu cầu hỗ trợ, admin xử lý và buộc đổi lại', async () => {
    const known = await call('/auth/request-password-reset', { body: { identifier: '0900000101' } });
    const unknown = await call('/auth/request-password-reset', { body: { identifier: '0900000999' } });
    assert.equal(known.message, unknown.message);
    const requests = (await call('/manage/password-requests', { token: admin })).items;
    const request = requests.find(item => Number(item.userId) === Number(candidateId)); assert.ok(request);
    const reset = await call(`/manage/users/${candidateId}/reset-password`, { token: admin, body: { requestId: request.id } });
    await call('/auth/me', { token: candidate, status: 401 });
    const login = await call('/auth/login', { body: { identifier: '0900000101', password: reset.temporaryPassword } });
    assert.equal(login.user.must_change_password, true);
    await call('/candidate/competitions', { token: login.token, status: 403 });
  });
});
